### ISSUE TITLE
GoFunc as new Action Destination

### ISSUE THREAD

**Issue by 0x41gawor** [0x41gawor/lupus#14]
- [x] Create new type of Destination called `gofunc`.
- [x] Research how it can be implemented. Does GO allow dynamic func name resolution? Will user only implement func with certain name and use this name in LupN or is he forced to modify Lupus code (more precisely Decide controller)
- [x] Implement

**Comment by 0x41gawor** [comment]
First we need to design the func signature.

It will be used in Action Send. Let's review it.

```yaml
actions:
  - name: sample
    type: send
    send: 
      inputKey: "elo"
      outputKey: "elo"
      destination:
         type: goFunc
         goFunc: 
           name:
```

And ok, signature can be derived from this pic:
![image](https://github.com/user-attachments/assets/9d40e8c2-2774-4a25-8e0e-1e4b4b9e7d0f)

So the signature is goint to be

```go
func(input interface{}) (interface{}, error)
```
