### ISSUE TITLE
New Action type Insert

### ISSUE THREAD

**Issue by 0x41gawor** [0x41gawor/lupus#15]
It would be nice to have action that can Insert a field in Data. Normally Data fields come from Manged-Systems or External-Systems. But what if we would like to have reflected in result Data the path that loop has taken?

```yaml
- actions:
    - name: "log-path"
      type: insert
        insert:
            field: "log.path_taken"
            value: "A"
```

Huh?

**Comment by 0x41gawor** [comment]
```yaml
- insert:
  field: "log.path_taken"
  type: string   
     string: 
        value: "A"
```
